module.exports = [
  {
    title: "Fried Anchovies with Sage",
    id: 1,
    image: "https://spoonacular.com/recipeImages/1-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Carrots, Cauliflower And Anchovies",
    id: 3,
    image: "https://spoonacular.com/recipeImages/3-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 2
  },
  {
    title: "Bap Story: Stir Fried Anchovies (Myulchi Bokkeum)",
    id: 4,
    image: "https://spoonacular.com/recipeImages/4-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 3
  },
  {
    title: "Bread, Butter And Anchovies",
    id: 5,
    image: "https://spoonacular.com/recipeImages/5-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 4
  },
  {
    title: "Fried Anchovies",
    id: 6,
    image: "https://spoonacular.com/recipeImages/6-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 5
  },
  {
    title: "Tomato & Anchovies With Bread Crumbs, Basil & Red Onion   Recip",
    id: 7,
    image: "https://spoonacular.com/recipeImages/7-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 6
  },
  {
    title: "Spaghetti With Walnuts And Anchovies",
    id: 11,
    image: "https://spoonacular.com/recipeImages/11-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 7
  },
  {
    title: "Anchovies, Tomatoes And Green Beans Couscous",
    id: 13,
    image: "https://spoonacular.com/recipeImages/13-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 8
  },
  {
    title: "Savory Slow Roasted Tomatoes with Filet of Anchovy",
    id: 17,
    image: "https://spoonacular.com/recipeImages/17-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 9
  },
  {
    title: "Anchovies, Beans And Rocket",
    id: 21,
    image: "https://spoonacular.com/recipeImages/21-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 10
  },
  {
    title: "Anchovy Fries with Smoked Paprika Aioli",
    id: 25,
    image: "https://spoonacular.com/recipeImages/25-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 11
  },
  {
    title: "Sliced Baguette With Radishes And Anchovy Butter",
    id: 26,
    image: "https://spoonacular.com/recipeImages/26-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 12
  },
  {
    title: "Cook the Book: Braided Beef with Anchovies and Olives",
    id: 27,
    image: "https://spoonacular.com/recipeImages/27-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 13
  },
  {
    title: "Potato Salad With Green Goddess Dressing",
    id: 28,
    image: "https://spoonacular.com/recipeImages/28-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    diets: ["vegetarian", "gluten free", "paleo"],
    health: 14
  },
  {
    title: "Skate, Chicory, and Anchovy",
    id: 29,
    image: "https://spoonacular.com/recipeImages/29-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 15
  },
  {
    title: "Caramelized Onion And Fresh Anchovy Tart",
    id: 31,
    image: "https://spoonacular.com/recipeImages/31-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 16
  },
  {
    title: "Anchovy Crostini With Onion-and-raisin Relish",
    id: 32,
    image: "https://spoonacular.com/recipeImages/32-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,diets: ["vegetarian", "vegan", "paleo"],
    health: 17
  },
  {
    title: "Radish Salad Lugano",
    id: 33,
    image: "https://spoonacular.com/recipeImages/33-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 18
  },
  {
    title: "Cardoons With Anchovy-garlic Sauce",
    id: 34,
    image: "https://spoonacular.com/recipeImages/34-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 19
  },
  {
    title: "Anchovy and Herb Marinade",
    id: 35,
    image: "https://spoonacular.com/recipeImages/35-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 20
  },
  {
    title: "Roasted Cauliflower With Anchovy Bread Crumbs",
    id: 37,
    image: "https://spoonacular.com/recipeImages/37-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Onion Anchovy Galette",
    id: 38,
    image: "https://spoonacular.com/recipeImages/38-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Radish Salad With Anchovy Sauce",
    id: 39,
    image: "https://spoonacular.com/recipeImages/39-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Pizza With Anchovies, Red Onion, And Oregano",
    id: 40,
    image: "https://spoonacular.com/recipeImages/40-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Grilled Mozzarella Sandwich With Anchovy-olive Tapenade",
    id: 42,
    image: "https://spoonacular.com/recipeImages/42-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: false,
    dairyFree: false,
    diets: ["gluten free", "whole 30", "ketogenic"],
    health: 1
  },
  {
    title: "Chicory In Anchovy Sauce",
    id: 44,
    image: "https://spoonacular.com/recipeImages/44-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["vegetarian", "vegan", "paleo"],
    health: 1
  },
  {
    title: "Roasted Cauliflower With Anchovy Vinaigrette",
    id: 47,
    image: "https://spoonacular.com/recipeImages/47-556x370.jpg",
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    diets: ["pescatarian", "whole 30", "paleo"],
    health: 1
  },
  {
    title: "Roasted Red Peppers With Anchovies And Olive Oil",
    id: 48,
    image: "https://spoonacular.com/recipeImages/48-556x370.jpg",
    vegetarian: false,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    diets: ["pescatarian", "whole 30", "paleo"],
    health: 1
  },
];
